#!/usr/bin/env bash
# project-analyzer.sh — Auto-discover projects for tmux-claude
#
# Scans known project root dirs for git repos / Node / Python / Rust / Go projects
# and writes ~/.config/tmux-claude/projects.conf in the format read by c-menu:
#   SessionName|/absolute/path|category
#
# Usage:
#   project-analyzer.sh                  # scan defaults, write conf
#   project-analyzer.sh --dry-run        # preview without writing
#   project-analyzer.sh --root PATH      # add an extra scan root (repeatable)
#   project-analyzer.sh --category NAME  # category for --root (default: work)

set -euo pipefail

CONFIG_DIR="$HOME/.config/tmux-claude"
CONF_FILE="$CONFIG_DIR/projects.conf"
DRY_RUN=false
EXTRA_ROOTS=()
EXTRA_CAT="work"

YEL=$'\033[1;33m'; GRN=$'\033[1;32m'; DIM=$'\033[2m'; RST=$'\033[0m'

usage() {
  sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
  exit 0
}

while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    --root) EXTRA_ROOTS+=("$2"); shift 2 ;;
    --category) EXTRA_CAT="$2"; shift 2 ;;
    -h|--help) usage ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done

mkdir -p "$CONFIG_DIR"

# ── Default scan roots: (path, category) ─────────────────────────────────
declare -a ROOTS_PATHS ROOTS_CATS
add_root() {
  local p="$1" c="$2"
  [ -d "$p" ] || return 0
  ROOTS_PATHS+=("$p"); ROOTS_CATS+=("$c")
}

# Common dev folders + tmux-claude conventions
add_root "$HOME/VibeCoding/work"     work
add_root "$HOME/VibeCoding/clients"  clients
add_root "$HOME/VibeCoding/1-life"   life
add_root "$HOME/projects"            work
add_root "$HOME/code"                work
add_root "$HOME/work"                work
add_root "$HOME/dev"                 work
add_root "$HOME/repos"               work
add_root "$HOME/src"                 work

for i in "${!EXTRA_ROOTS[@]}"; do
  add_root "${EXTRA_ROOTS[$i]}" "$EXTRA_CAT"
done

if [ ${#ROOTS_PATHS[@]} -eq 0 ]; then
  echo "  ${YEL}No project roots found.${RST} Use --root PATH to add one." >&2
  exit 1
fi

# ── Detect: dir is a "project" if it contains any of these markers ──────
is_project_dir() {
  local d="$1"
  [ -d "$d/.git" ]            && return 0
  [ -f "$d/package.json" ]    && return 0
  [ -f "$d/pyproject.toml" ]  && return 0
  [ -f "$d/Cargo.toml" ]      && return 0
  [ -f "$d/go.mod" ]          && return 0
  [ -f "$d/Gemfile" ]         && return 0
  [ -f "$d/composer.json" ]   && return 0
  [ -f "$d/pubspec.yaml" ]    && return 0
  [ -f "$d/requirements.txt" ] && return 0
  return 1
}

# Stack detection for the comment line
detect_stack() {
  local d="$1"
  local stacks=()
  [ -f "$d/next.config.js" ] || [ -f "$d/next.config.ts" ] || [ -f "$d/next.config.mjs" ] && stacks+=("Next.js")
  [ -f "$d/vite.config.ts" ] || [ -f "$d/vite.config.js" ] && stacks+=("Vite")
  [ -f "$d/svelte.config.js" ] && stacks+=("Svelte")
  [ -f "$d/nuxt.config.ts" ] || [ -f "$d/nuxt.config.js" ] && stacks+=("Nuxt")
  [ -f "$d/Cargo.toml" ] && stacks+=("Rust")
  [ -f "$d/go.mod" ] && stacks+=("Go")
  [ -f "$d/pyproject.toml" ] || [ -f "$d/requirements.txt" ] && stacks+=("Python")
  [ -f "$d/Gemfile" ] && stacks+=("Ruby")
  if [ ${#stacks[@]} -eq 0 ] && [ -f "$d/package.json" ]; then stacks+=("Node"); fi
  (IFS=,; echo "${stacks[*]:-generic}")
}

# Sanitize folder name → tmux-friendly session name (no spaces, no /)
sanitize_name() {
  local n="$1"
  n="${n// /-}"
  n="${n//\//-}"
  echo "$n"
}

# ── Scan ────────────────────────────────────────────────────────────────
declare -A SEEN
ENTRIES=""
COUNT=0

register() {
  local d="$1" cat="$2"
  local base; base=$(basename "$d")
  local name; name=$(sanitize_name "$base")
  local key="$name|$d"
  [ -n "${SEEN[$key]:-}" ] && return 0
  SEEN[$key]=1
  local stack; stack=$(detect_stack "$d")
  ENTRIES+="${name}|${d}|${cat}|${stack}"$'\n'
  COUNT=$((COUNT+1))
}

scan_root() {
  local root="$1" cat="$2"
  # If the root itself is a project (e.g. ~/VibeCoding/1-life is a git repo), register it.
  if is_project_dir "$root"; then
    register "$root" "$cat"
    return 0
  fi
  # Otherwise, scan direct children. Skip hidden dirs.
  while IFS= read -r -d '' d; do
    local base; base=$(basename "$d")
    [[ "$base" == .* ]] && continue
    is_project_dir "$d" || continue
    register "$d" "$cat"
  done < <(find "$root" -maxdepth 1 -mindepth 1 -type d -print0 2>/dev/null)
}

for i in "${!ROOTS_PATHS[@]}"; do
  scan_root "${ROOTS_PATHS[$i]}" "${ROOTS_CATS[$i]}"
done

if [ "$COUNT" -eq 0 ]; then
  echo "  ${YEL}No projects detected.${RST}" >&2
  exit 1
fi

# ── Compose conf file ───────────────────────────────────────────────────
TMP_CONF=$(mktemp)
{
  echo "# Project Registry — generated by project-analyzer.sh"
  echo "# Format: SessionName|/absolute/path|category"
  echo "# Categories: work | clients | life"
  echo "# Generated: $(date -Iseconds)"
  echo ""

  for cat in work clients life; do
    local_section=$(echo "$ENTRIES" | awk -F'|' -v c="$cat" '$3==c{print $1"|"$2"|"$3"  # "$4}' | sort -f)
    [ -z "$local_section" ] && continue
    echo "# === ${cat^} ==="
    echo "$local_section"
    echo ""
  done
} > "$TMP_CONF"

# ── Output / Write ──────────────────────────────────────────────────────
if $DRY_RUN; then
  echo "  ${DIM}# Dry-run preview ($COUNT projects):${RST}"
  cat "$TMP_CONF"
  rm -f "$TMP_CONF"
  exit 0
fi

mv "$TMP_CONF" "$CONF_FILE"
echo "  ${GRN}✓${RST} Wrote ${YEL}$COUNT${RST} projects to ${DIM}$CONF_FILE${RST}"
