#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════
# Session Manager v4 — Grouped, protected, with kill history
# Enter=switch  x=kill  .=protect  §=refresh  Esc=close
# ══════════════════════════════════════════════════════════════

# Render-only mode for fzf `reload(...)` action — outputs DISPLAY_LIST to stdout
# and exits before the fzf invocation. Used by the § bind to refresh in-place.
SM_RENDER_MODE=""
if [ "${1:-}" = "--render" ]; then
    SM_RENDER_MODE="list"
    shift
    VIEW_ARG="${1:-sessions}"
fi

CURRENT_SESSION=$(tmux display-message -p '#S')
NOW=$(date +%s)
TMPDIR_SM="/tmp/.sm-$$"
PROTECT_DIR="/tmp/.tmux-protected"
HISTORY_FILE="/tmp/.tmux-kill-history"
AUTOPROTECT_DIR="/tmp/.tmux-autoprotect"
mkdir -p "$TMPDIR_SM" "$PROTECT_DIR" "$AUTOPROTECT_DIR"
trap "rm -rf '$TMPDIR_SM'" EXIT
touch "$HISTORY_FILE"

# ── Project → category map from projects.json ──
# Used to bucket sessions into work / clients / life / aisb.
# Sessions whose project_key isn't in projects.json fall back to "aisb"
# (i.e. "stuff outside current context").
declare -A PROJECT_CAT
# Project registry — primary source: ~/.config/tmux-claude/projects.conf
# (generated by project-analyzer.sh on install). Optional fallback: AISB
# projects.json if present (legacy / local override).
PROJECTS_CONF="$HOME/.config/tmux-claude/projects.conf"
PROJECTS_JSON="$HOME/VibeCoding/agentic/agentik-monitor/bot/projects.json"
if [ -f "$PROJECTS_CONF" ]; then
    while IFS='|' read -r pname ppath pcat _rest; do
        [[ "$pname" == \#* || -z "$pname" ]] && continue
        ppath="${ppath%%#*}"; ppath="${ppath%%[[:space:]]}"
        pcat="${pcat%%[[:space:]]*}"
        [ -n "$pcat" ] && PROJECT_CAT[$pname]="$pcat"
    done < "$PROJECTS_CONF"
fi
if [ -f "$PROJECTS_JSON" ] && command -v jq >/dev/null 2>&1; then
    while IFS='|' read -r pname ppath; do
        [ -n "${PROJECT_CAT[$pname]:-}" ] && continue   # don't override conf
        case "$ppath" in
            */work/*)     PROJECT_CAT[$pname]="work" ;;
            */clients/*)  PROJECT_CAT[$pname]="clients" ;;
            */1-life*)    PROJECT_CAT[$pname]="life" ;;
        esac
    done < <(jq -r '.projects | to_entries[] | "\(.key)|\(.value.path)"' "$PROJECTS_JSON" 2>/dev/null)
fi

# Known multi-segment project keys (longest first) so `project_key` doesn't
# truncate names like `Agentik-Academy-worker-…` to `Agentik`. Without this,
# any project whose name contains a hyphen (Agentik-Academy, CAIO-Academy, …)
# would have its workers grouped under the wrong bucket in the session menu.
KNOWN_PROJECTS=()
if [ -f "$PROJECTS_JSON" ] && command -v jq >/dev/null 2>&1; then
    while IFS= read -r _pkey; do
        [ -n "$_pkey" ] && KNOWN_PROJECTS+=("$_pkey")
    done < <(jq -r '.projects | keys[]' "$PROJECTS_JSON" 2>/dev/null \
             | awk '{ print length, $0 }' | sort -rn | cut -d' ' -f2-)
fi

project_category() {
    local pkey="$1"
    case "$pkey" in
        Home)    echo "home";    return ;;
        _system) echo "aisb";    return ;;
    esac
    local cat="${PROJECT_CAT[$pkey]}"
    if [ -n "$cat" ]; then echo "$cat"; else echo "aisb"; fi
}

# Terminal width for adaptive columns
# In --render mode (fzf reload child) tput has no tty → use the parent's TERM_W
# passed via env var. Otherwise probe the actual terminal/popup width.
TERM_W=${SM_TERM_W:-$(tput cols 2>/dev/null || echo 80)}

# Dynamic NAME_MAX: use all available terminal width.
# Right-side fixed cost: ram(5) + age(6) + branch(10) + 3 inter-col spaces = 24
# Left prefix cost: 2-space indent + marker(1) + space + icon(1) + space + protect(1) + space = 8
# Double-space after name = 2
# Total fixed = 34 → NAME_MAX = TERM_W - 34
NAME_MAX=$((TERM_W - 65))    # default: name area + age bar + progress + ram + age + branch + gutters
[ "$NAME_MAX" -lt 18 ] && NAME_MAX=18
[ "$NAME_MAX" -gt 50 ] && NAME_MAX=50    # generous cap — fits ~99% of session names without truncation
                                          # while keeping the whole row packed (no big gaps anywhere)
PATH_MAX=$((TERM_W - 60))
[ "$PATH_MAX" -lt 8 ] && PATH_MAX=8

# short_name: when a session is rendered inside a tree (its project parent is
# already visible above), strip the redundant project prefix from the display.
# The full session name is still preserved in the hidden TAB field for
# tmux switch-client and for search.
short_name() {
    local name="$1" pkey="$2"
    [ -z "$pkey" ] && { REPLY="$name"; return; }
    case "$name" in
        oracle-"${pkey}")          REPLY="oracle"; return ;;
        oracle-"${pkey}"-*)        REPLY="oracle-${name#oracle-${pkey}-}"; return ;;
        "${pkey}"-oracle)          REPLY="oracle"; return ;;
        "${pkey}"-oracle-*)        REPLY="oracle-${name#${pkey}-oracle-}"; return ;;
        "${pkey}"-worker-*)        REPLY="${name#${pkey}-}"; return ;;
    esac
    REPLY="$name"
}

# All helper functions write to $REPLY (bash convention) — eliminates the
# subshell fork from $(func "$arg") in hot loops. ~10× speed-up at scale.
truncate_str() {
    local str="$1" max="$2"
    if [ "${#str}" -gt "$max" ]; then
        REPLY="${str:0:$((max-1))}…"
    else
        REPLY="$str"
    fi
}

# truncate_smart: keep right side if mode=start (preserves ticket IDs like CAU-95).
truncate_smart() {
    local str="$1" max="$2" mode="${3:-end}"
    if [ "${#str}" -le "$max" ]; then
        REPLY="$str"
        return
    fi
    if [ "$mode" = "start" ]; then
        REPLY="…${str: -$((max-1))}"
    else
        REPLY="${str:0:$((max-1))}…"
    fi
}

# ANSI helpers for warnings (only place color is permitted by user policy).
RED=$'\033[31m'
YEL=$'\033[33m'
RST=$'\033[0m'

human_time() {
    local secs=$1
    if   [ "$secs" -lt 60 ];    then REPLY="${secs}s"
    elif [ "$secs" -lt 3600 ];  then REPLY="$((secs/60))m"
    elif [ "$secs" -lt 86400 ]; then REPLY="$((secs/3600))h$((secs%3600/60))m"
    else                              REPLY="$((secs/86400))d$((secs%86400/3600))h"
    fi
}

# Bulk-load AISB progress state for ALL sessions in ONE awk pass over every
# progress.json file. ~110 files processed in one fork instead of bash reading
# each file line-by-line (was the dominant render cost on hosts with many
# orchestration files). Populates global PROGRESS_STATE keyed by session name.
load_all_progress() {
    unset PROGRESS_STATE 2>/dev/null
    declare -gA PROGRESS_STATE
    shopt -s nullglob
    local files=( "$HOME/.aisb/state/oracle-"*.progress.json "$HOME/.aisb/state/worker-"*.progress.json )
    shopt -u nullglob
    [ ${#files[@]} -eq 0 ] && return
    while IFS='|' read -r sname pstr; do
        [ -n "$sname" ] && PROGRESS_STATE[$sname]="$pstr"
    done < <(awk '
        FNR == 1 {
            # Extract session name from filename
            base = FILENAME
            sub(/.*\//, "", base)
            sub(/\.progress\.json$/, "", base)
            sub(/^oracle-/, "", base)
            sub(/^worker-/, "", base)
            sname = base
            sessions[sname] = 1
            total[sname] = ""
            done_n[sname] = ""
            blocked[sname] = 0
        }
        /"todos_total"/ {
            n = match($0, /[0-9]+/)
            if (n) total[sname] = substr($0, RSTART, RLENGTH)
        }
        /"todos_completed"/ {
            n = match($0, /[0-9]+/)
            if (n) done_n[sname] = substr($0, RSTART, RLENGTH)
        }
        /"status"[[:space:]]*:[[:space:]]*"blocked"/ { blocked[sname] = 1 }
        END {
            for (s in sessions) {
                if (total[s] != "" && total[s] != "0") {
                    suffix = blocked[s] ? "⚠" : ""
                    printf "%s|%s/%s%s\n", s, done_n[s], total[s], suffix
                }
            }
        }
    ' "${files[@]}" 2>/dev/null)
}

# 8-char age bar — log-ish scale on 0..24h.
#   <5min=1 ▰ | <15min=2 | <1h=3 | <3h=4 | <8h=5 | <12h=6 | <24h=7 | >=24h=8
age_bar() {
    local secs="${1:-0}" n=0
    if   [ "$secs" -lt 300 ];   then n=1
    elif [ "$secs" -lt 900 ];   then n=2
    elif [ "$secs" -lt 3600 ];  then n=3
    elif [ "$secs" -lt 10800 ]; then n=4
    elif [ "$secs" -lt 28800 ]; then n=5
    elif [ "$secs" -lt 43200 ]; then n=6
    elif [ "$secs" -lt 86400 ]; then n=7
    else                              n=8
    fi
    local out="" i=0
    while [ "$i" -lt 8 ]; do
        if [ "$i" -lt "$n" ]; then out+="▰"; else out+="▱"; fi
        i=$((i+1))
    done
    REPLY="$out"
}

human_mb() {
    local kb=$1
    if   [ "$kb" -lt 1024 ];    then REPLY="${kb}K"
    elif [ "$kb" -lt 1048576 ]; then REPLY="$((kb/1024))M"
    else
        local g=$((kb / 1048576))
        local d=$(( (kb % 1048576) * 10 / 1048576 ))
        REPLY="${g}.${d}G"
    fi
}

is_protected() {
    [ -f "$PROTECT_DIR/$1" ]
}

toggle_protection() {
    local sess="$1"
    if is_protected "$sess"; then
        rm -f "$PROTECT_DIR/$sess"
    else
        touch "$PROTECT_DIR/$sess"
    fi
}

# ── Auto-protect: protect working sessions, unprotect idle >10min ──
auto_protect_check() {
    local sess="$1" status="$2"
    local ap_file="$AUTOPROTECT_DIR/$sess"
    if [ "$status" = "work" ]; then
        # Auto-protect if working and not manually unprotected
        if [ ! -f "$PROTECT_DIR/${sess}.manual-unprotect" ]; then
            touch "$PROTECT_DIR/$sess"
            touch "$ap_file"  # mark as auto-protected
        fi
    elif [ "$status" = "idle" ] && [ -f "$ap_file" ]; then
        # Was auto-protected, now idle — check if idle >10min
        local ap_age=$(( NOW - $(stat -c %Y "$ap_file" 2>/dev/null || echo "$NOW") ))
        if [ "$ap_age" -gt 600 ]; then
            rm -f "$PROTECT_DIR/$sess" "$ap_file"
        fi
    fi
}

# ── Kill with history logging ──
kill_with_history() {
    local sess="$1"
    local reason="${2:-manual}"
    # Log to history (keep last 20)
    echo "$(date '+%H:%M:%S') | $sess | $reason" >> "$HISTORY_FILE"
    tail -20 "$HISTORY_FILE" > "$HISTORY_FILE.tmp" && mv "$HISTORY_FILE.tmp" "$HISTORY_FILE"
    tmux kill-session -t "$sess" 2>/dev/null
}

# ── RAM usage for a session (awk tree walk over shared PS_SNAP, zero forks) ──
get_session_ram() {
    local sess="$1" outfile="$2"
    local pane_pids
    # Read pane_pids from batched PANES_SNAP instead of forking tmux per session
    pane_pids=$(awk -F'\t' -v s="$sess" '$1==s{print $2}' "$PANES_SNAP" 2>/dev/null | tr '\n' ' ')
    if [ -z "$pane_pids" ] || [ ! -f "$PS_SNAP" ]; then
        echo 0 > "$outfile"
        return
    fi
    # Full tree walk via awk: sum RSS of all descendants of pane_pids
    awk -v roots="$pane_pids" '
        { ppid=$2; pid=$1; rss[pid]=$3; child[ppid]=child[ppid]" "pid }
        END {
            n=split(roots, r, " ")
            total=0
            for (i=1; i<=n; i++) if (r[i]!="") { q[++qn]=r[i] }
            while (qn>0) {
                cur=q[qn]; qn--
                m=split(child[cur], kids, " ")
                for (j=1; j<=m; j++) {
                    k=kids[j]
                    if (k!="") { total += rss[k]; q[++qn]=k }
                }
            }
            print total
        }' "$PS_SNAP" > "$outfile"
}

# ── Deep Claude status detection (uses PS_SNAP + PANES_SNAP, zero ps/pgrep/tmux forks) ──
detect_claude_status() {
    local session="$1" outfile="$2"
    local result="" detail=""

    # Read panes for this session from batched snapshot
    local pane_claude_parents=""
    pane_claude_parents=$(awk -F'\t' -v s="$session" '$1==s && $3=="claude"{print $2}' "$PANES_SNAP" 2>/dev/null | tr '\n' ' ')

    if [ -z "$pane_claude_parents" ] || [ ! -f "$PS_SNAP" ]; then
        echo "shell|0|0|" > "$outfile"
        return
    fi

    # One awk call computes: claude_count, total_cpu, subagent_count, real_work tool
    local stats
    stats=$(awk -v roots="$pane_claude_parents" '
        BEGIN {
            n=split(roots, r, " ")
            for (i=1; i<=n; i++) if (r[i]!="") rootset[r[i]]=1
            # ignored commands when checking real_work
            ignore="ps sleep cat grep tail head wc sed awk echo test zsh bash sh tee tr sort xargs date timeout node claude npm npx tsx"
            ni=split(ignore, ig, " "); for (i=1; i<=ni; i++) ignored[ig[i]]=1
        }
        {
            pid=$1; ppid=$2; cpu=$4; comm=$5
            rss_idx=3 # unused here
            child[ppid]=child[ppid]" "pid
            pcomm[pid]=comm
            pcpu[pid]=cpu
        }
        END {
            claude_count=0; subagent_count=0; total_cpu=0; real_work=0; work_tool=""
            # top-level claude PIDs = direct children of pane pids whose comm is "claude"
            delete claude_pids
            for (pp in rootset) {
                m=split(child[pp], kids, " ")
                for (j=1; j<=m; j++) {
                    k=kids[j]
                    if (k!="" && pcomm[k]=="claude") {
                        claude_pids[k]=1
                        claude_count++
                    }
                }
            }
            if (claude_count==0) { print "shell|0|0|"; exit }

            # Walk full descendant tree of all claude_pids
            for (cp in claude_pids) {
                total_cpu += int(pcpu[cp])
                # BFS
                qn=0; q[++qn]=cp
                while (qn>0) {
                    cur=q[qn]; qn--
                    m=split(child[cur], kids, " ")
                    for (j=1; j<=m; j++) {
                        k=kids[j]
                        if (k=="") continue
                        q[++qn]=k
                        kc=pcomm[k]
                        if (kc=="claude") subagent_count++
                        if (!real_work && !(kc in ignored)) {
                            # skip mcp-*, firecrawl*, chrome-*, playwright* prefixes
                            if (kc !~ /^(mcp-|firecrawl|chrome-|playwright)/) {
                                real_work=1
                                work_tool=kc
                            }
                        }
                    }
                }
            }
            printf "OK|%d|%d|%d|%d|%s\n", claude_count, total_cpu, subagent_count, real_work, work_tool
        }' "$PS_SNAP")

    # Shell-only early exit path
    if [ "${stats%%|*}" = "shell" ]; then
        echo "shell|0|0|" > "$outfile"
        return
    fi

    local claude_count total_cpu subagent_count real_work work_tools
    IFS='|' read -r _ claude_count total_cpu subagent_count real_work work_tools <<< "$stats"

    # Fast path: decide without capture-pane if ps data is conclusive
    if [ "$subagent_count" -gt 0 ]; then
        result="work"; detail="${subagent_count}agents"
    elif [ "$real_work" -eq 1 ]; then
        result="work"; detail="${work_tools%% *}"
    elif [ "$total_cpu" -gt 15 ]; then
        result="work"; detail="cpu${total_cpu}%"
    else
        # Ambiguous: need a capture-pane to tell idle-at-prompt vs streaming
        last_lines=$(tmux capture-pane -t "$session" -p -S -6 2>/dev/null)
        has_prompt=0; is_streaming=0
        case "$last_lines" in *❯*) has_prompt=1 ;; esac
        case "$last_lines" in
            *"esc to interrupt"*|*"⏳"*) is_streaming=1 ;;
            *Thinking*|*Planning*)       is_streaming=1 ;;
        esac
        if [ "$is_streaming" -eq 1 ]; then
            result="work"; detail="stream"
        elif [ "$has_prompt" -eq 1 ]; then
            result="idle"; detail=""
        else
            result="work"; detail="active"
        fi
    fi

    echo "${result}|${subagent_count}|${claude_count}|${detail}" > "$outfile"
}

# ── Classify session into group ──
classify_session() {
    local name="$1"
    [[ "$name" == earthbit* ]] && { echo "system"; return; }
    [[ "$name" == AISB-* ]] && { echo "system"; return; }
    [[ "$name" == oracle-* ]] && { echo "oracle"; return; }
    [[ "$name" == Home* ]] && { echo "home"; return; }
    [[ "$name" == c-* ]] && { echo "home"; return; }
    echo "worker"
}

# ── Extract project key from session name (for grouping oracle+workers together) ──
# oracle-Causio         → Causio
# oracle-Causio-2       → Causio
# Causio-linear-CAU-42  → Causio
# Causio-fix-auth       → Causio
# DentistryGPT-verify   → DentistryGPT
# Home                  → Home
# Home-4                → Home
# earthbit-daemon       → _system
# AISB-bot              → _system
project_key() {
    local name="$1"
    case "$name" in
        earthbit*) REPLY="_system"; return ;;
        AISB-*)    REPLY="_system"; return ;;
        Home*)     REPLY="Home"; return ;;
        c-*)       REPLY="Home"; return ;;
    esac
    if [[ "$name" == oracle-* ]]; then
        local stripped="${name#oracle-}"
        stripped="${stripped%-[0-9]}"
        stripped="${stripped%-[0-9][0-9]}"
        REPLY="$stripped"
        return
    fi
    # Longest-prefix match against known multi-segment project keys so that
    # `Agentik-Academy-worker-B-…` groups under `Agentik-Academy`, not `Agentik`.
    local _proj
    for _proj in "${KNOWN_PROJECTS[@]}"; do
        case "$name" in
            "$_proj"|"$_proj"-*) REPLY="$_proj"; return ;;
        esac
    done
    REPLY="${name%%-*}"
}

project_role() {
    case "$1" in
        oracle-*)   REPLY=0 ;;
        *-oracle)   REPLY=0 ;;
        *-oracle-*) REPLY=0 ;;
        Home*)      REPLY=2 ;;
        c-*)        REPLY=2 ;;
        earthbit*)  REPLY=3 ;;
        AISB-*)     REPLY=3 ;;
        *)          REPLY=1 ;;
    esac
}

oracle_idx() {
    case "$1" in
        oracle-*-[0-9]|oracle-*-[0-9][0-9])  REPLY="${1##*-}"; return ;;
        oracle-*)                             REPLY="1"; return ;;
        *-oracle-[0-9]|*-oracle-[0-9][0-9])  REPLY="${1##*-}"; return ;;
        *-oracle)                             REPLY="1"; return ;;
    esac
    if [[ "$1" == *-worker-* ]]; then
        local rest="${1#*-worker-}"
        local idx="${rest%%-*}"
        if [[ "$idx" =~ ^[0-9]+$ ]]; then REPLY="$idx"; return; fi
    fi
    REPLY="1"
}

# ── Show kill history ──
show_history() {
    if [ ! -s "$HISTORY_FILE" ]; then
        echo "  (no kill history)" | fzf --no-multi --reverse --no-info \
            --header="Kill History  Esc=back" --prompt="history > " --border=none \
            --color="fg:-1,bg:-1,hl:-1:underline,fg+:0:bold,bg+:7,hl+:1:bold:underline,info:-1,prompt:-1,pointer:-1,marker:-1,spinner:-1,header:-1:dim,border:-1,preview-fg:-1,preview-bg:-1,gutter:-1"
        return
    fi
    tac "$HISTORY_FILE" | fzf --no-multi --reverse --no-info \
        --header="Kill History (newest first)  Esc=back" \
        --prompt="history > " --pointer=" " --border=none \
        --color="fg:-1,bg:-1,hl:-1:underline,fg+:0:bold,bg+:7,hl+:1:bold:underline,info:-1,prompt:-1,pointer:-1,marker:-1,spinner:-1,header:-1:dim,border:-1,preview-fg:-1,preview-bg:-1,gutter:-1"
}

show_help() {
    local help_text=""
    help_text+="  SESSION MANAGER — Keyboard Shortcuts"
    help_text+=$'\n'"  ──────────────────────────────────────────"
    help_text+=$'\n'""
    help_text+=$'\n'"  Tabs"
    help_text+=$'\n'"  ← or <       Previous tab"
    help_text+=$'\n'"  → or >       Next tab (sessions ↔ menu ↔ help)"
    help_text+=$'\n'""
    help_text+=$'\n'"  Navigation"
    help_text+=$'\n'"  ↑ / ↓        Move between sessions (skips blanks + headers)"
    help_text+=$'\n'"  Tab          Jump to next project group"
    help_text+=$'\n'"  ⇧Tab         Spawn new ClaudeRoot session at \$HOME"
    help_text+=$'\n'"  Enter        Switch to selected session / run menu action"
    help_text+=$'\n'"  Esc          Close this menu"
    help_text+=$'\n'""
    help_text+=$'\n'"  Session Actions"
    help_text+=$'\n'"  x            Kill selected session"
    help_text+=$'\n'"  .            Toggle kill protection (§)"
    help_text+=$'\n'"  §            Refresh preview pane"
    help_text+=$'\n'""
    help_text+=$'\n'"  Status Icons"
    help_text+=$'\n'"  ●  working   Claude is actively running"
    help_text+=$'\n'"  ○  idle      Claude at prompt, waiting"
    help_text+=$'\n'"  ·  shell     No Claude in this session"
    help_text+=$'\n'"  §  protected Immune to orphan-killer & x"
    help_text+=$'\n'""
    help_text+=$'\n'"  Tree Glyphs (oracle + workers grouping)"
    help_text+=$'\n'"  ├ / └        Worker belongs to the oracle above"
    help_text+=$'\n'"               (drawn only when group has both oracle and worker)"
    help_text+=$'\n'""
    help_text+=$'\n'"  Project Groups"
    help_text+=$'\n'"  Home         Home, Home-2, c-* (interactive sessions)"
    help_text+=$'\n'"  <Project>    Each project gets its own header (Causio, Kommu, …)"
    help_text+=$'\n'"  system       earthbit-*, AISB-* (orchestration daemons)"
    help_text+=$'\n'""
    help_text+=$'\n'"  Menu Tab Actions (open with > > or via tab nav)"
    help_text+=$'\n'"  open project Pick a project from projects.json"
    help_text+=$'\n'"  clean RAM    Drop caches + clear /tmp junk"
    help_text+=$'\n'"  kill all     Kill every session except current"
    help_text+=$'\n'""
    help_text+=$'\n'"  Auto-Protect"
    help_text+=$'\n'"  Working sessions are auto-protected."
    help_text+=$'\n'"  After 10 min idle, protection is removed."
    help_text+=$'\n'"  Manual . override is respected."
    help_text+=$'\n'""
    help_text+=$'\n'"  Status Bar (top right)"
    help_text+=$'\n'"  cpu / ram / disk percentages, total RAM consumed by sessions"

    echo "$help_text" | fzf \
        --no-multi --reverse --no-info --disabled \
        --header="Help  │  Esc=back" \
        --pointer=" " --border=none \
        --color="fg:-1,bg:-1,hl:-1:underline,fg+:0:bold,bg+:7,hl+:1:bold:underline,info:-1,prompt:-1,pointer:-1,marker:-1,spinner:-1,header:-1:dim,border:-1,preview-fg:-1,preview-bg:-1,gutter:-1"
}

show_close_menu() {
    local all_sessions=$(tmux list-sessions -F '#{session_name}' 2>/dev/null)
    unset PROJECT_GROUPS 2>/dev/null; declare -A PROJECT_GROUPS
    for s in $all_sessions; do
        local base=$(echo "$s" | sed 's/-[0-9]*$//')
        PROJECT_GROUPS["$base"]+="$s "
    done

    local menu=""
    for base in $(echo "${!PROJECT_GROUPS[@]}" | tr ' ' '\n' | sort); do
        local sessions="${PROJECT_GROUPS[$base]}"
        local count=$(echo "$sessions" | wc -w)
        local marker=" "
        for s in $sessions; do
            [ "$s" = "$CURRENT_SESSION" ] && marker=">" && break
        done
        truncate_str "$base" 22; local tbase="$REPLY"
        printf -v line "%s  %-22s  %d session%s" "$marker" "$tbase" "$count" "$([ $count -gt 1 ] && echo 's' || echo '')"
        [ -n "$menu" ] && menu="${menu}"$'\n'"${line}" || menu="${line}"
    done

    local selected=$(echo "$menu" | fzf \
        --multi --reverse --no-info \
        --header="Tab=select  Enter=close  Esc=back" \
        --prompt="close > " --pointer=">" --marker="x" --border=none \
        --preview="base=\$(echo {} | sed 's/^[^ ]* *//' | sed 's/  .*//' | xargs); echo \"\$base sessions:\"; echo; tmux list-sessions -F '#{session_name}' 2>/dev/null | grep \"^\${base}\" | while read s; do ppath=\$(tmux display-message -t \"\$s\" -p '#{pane_current_path}' 2>/dev/null | sed \"s|\$HOME|~|\"); cmd=\$(tmux list-panes -t \"\$s\" -F '#{pane_current_command}' 2>/dev/null | head -1); echo \"  \$s  (\$cmd)  \$ppath\"; done" \
        --preview-window=down,40%,wrap \
        --color="fg:-1,bg:-1,hl:-1:underline,fg+:0:bold,bg+:7,hl+:1:bold:underline,info:-1,prompt:-1,pointer:-1,marker:-1,spinner:-1,header:-1:dim,border:-1,preview-fg:-1,preview-bg:-1,gutter:-1")

    [ -z "$selected" ] && return 0

    local to_kill=""
    while read -r line; do
        local base=$(echo "$line" | sed 's/^[^ ]* *//' | sed 's/  .*//' | xargs)
        to_kill+="${PROJECT_GROUPS[$base]}"
    done <<< "$selected"

    for s in $to_kill; do
        [ "$s" != "$CURRENT_SESSION" ] && kill_with_history "$s" "close-menu"
    done

    if [[ " $to_kill " == *" $CURRENT_SESSION "* ]]; then
        local other=$(tmux list-sessions -F '#{session_name}' 2>/dev/null | grep -v "^${CURRENT_SESSION}$" | head -1)
        if [ -n "$other" ]; then
            tmux switch-client -t "$other"
            kill_with_history "$CURRENT_SESSION" "close-menu"
            CURRENT_SESSION="$other"
        fi
    fi
    return 1
}

# ── Extract session name from display line ──
# Primary path: read the hidden field after the trailing TAB (full name, untruncated).
# Fallback: parse the visible portion (legacy path; ignore tree chars + markers).
extract_name() {
    local line="$1"
    case "$line" in
        *$'\t'*) printf '%s' "${line##*$'\t'}"; return ;;
    esac
    echo "$line" | awk '{for(i=1;i<=NF;i++){if($i!=">" && $i!="*" && $i!="●" && $i!="○" && $i!="·" && $i!="§" && $i!="│" && $i!="├" && $i!="└" && $i!="✗" && $i!="L" && $i!="🔒"){print $i; exit}}}'
}

# ══════════════════════════════════════════
# ── Main loop ──
# ══════════════════════════════════════════

# Top-level view. Switch with ←/→ or </>
VIEW="${VIEW_ARG:-sessions}"   # sessions | menu | help

# Render the tab bar — browser-style underline (Option C).
# Two lines: labels on top, heavy ━━━ underline only beneath the active label.
# No boxes, no borders → minimalist, modern. Active label is bold + underlined.
render_tabs() {
    local active="$1"
    local bold=$'\033[1m' rst=$'\033[0m'
    local labels=("sessions" "menu" "help")
    local gap="     "   # 5-space gap between labels
    local line1="" line2=""
    local first=1
    for label in "${labels[@]}"; do
        if [ $first -eq 0 ]; then
            line1+="$gap"
            line2+="$gap"
        fi
        first=0
        local n=${#label}
        local underline="" pad="" i=0
        while [ "$i" -lt "$n" ]; do underline+="━"; pad+=" "; i=$((i+1)); done
        if [ "$label" = "$active" ]; then
            line1+="${bold}${label}${rst}"
            line2+="${bold}${underline}${rst}"
        else
            line1+="$label"
            line2+="$pad"
        fi
    done
    printf '%s\n%s' "$line1" "$line2"
}

while true; do
    # Instant CPU from /proc/stat (was top -bn1 = 250ms fork)
    CPU=$(awk '/^cpu /{t=$2+$3+$4+$5+$6+$7+$8+$9; i=$5+$6; printf "%.0f", (1-i/t)*100}' /proc/stat 2>/dev/null)
    DISK=$(df -h / 2>/dev/null | awk 'NR==2{print $5}')
    RAM=$(free 2>/dev/null | awk '/Mem:/{printf "%.0f", $3/$2*100}')

    SESSION_DATA=$(tmux list-sessions -F '#{session_name}|#{session_windows}|#{session_attached}|#{session_activity}|#{session_created}' 2>/dev/null)
    [ -z "$SESSION_DATA" ] && exit 0

    # ── ONE ps snapshot shared across all sessions (was 200+ forks) ──
    PS_SNAP="$TMPDIR_SM/ps.snap"
    ps -eo pid,ppid,rss,pcpu,comm --no-headers 2>/dev/null > "$PS_SNAP"
    export PS_SNAP

    # ── ONE tmux list-panes -a call for ALL sessions (was N tmux calls in pass1) ──
    # Format: session<TAB>pane_pid<TAB>pane_current_command<TAB>pane_current_path
    PANES_SNAP="$TMPDIR_SM/panes.snap"
    tmux list-panes -a -F '#{session_name}	#{pane_pid}	#{pane_current_command}	#{pane_current_path}' 2>/dev/null > "$PANES_SNAP"
    export PANES_SNAP

    # ── Pre-aggregate panes count + first pane path per session in ONE awk pass ──
    # Eliminates 2 awk forks PER SESSION in Pass 1.
    unset SESSION_PANE_COUNT SESSION_PANE_PATH 2>/dev/null
    declare -A SESSION_PANE_COUNT SESSION_PANE_PATH
    while IFS=$'\t' read -r _s _c _p; do
        SESSION_PANE_COUNT[$_s]=$_c
        SESSION_PANE_PATH[$_s]=$_p
    done < <(awk -F'\t' '
        { cnt[$1]++; if (!path[$1]) path[$1] = $4 }
        END { for (s in cnt) printf "%s\t%d\t%s\n", s, cnt[s], path[s] }
    ' "$PANES_SNAP")

    # Status cache shared across rapid reopens (TTL 2 s) — skips the parallel
    # detect_claude_status block entirely when the cache is fresh, saving the
    # ~200 ms otherwise spent waiting for 35+ background subshells.
    STATUS_CACHE_DIR="/tmp/.tmux-sm-cache-${USER:-hacker}"
    mkdir -p "$STATUS_CACHE_DIR" 2>/dev/null
    CACHE_TS_FILE="$STATUS_CACHE_DIR/.ts"
    NOW_S=$(date +%s)
    CACHE_AGE=999
    [ -f "$CACHE_TS_FILE" ] && CACHE_AGE=$((NOW_S - $(stat -c %Y "$CACHE_TS_FILE" 2>/dev/null || echo 0)))
    # § (--render) is an explicit on-demand refresh — always force fresh detect
    [ "$SM_RENDER_MODE" = "list" ] && CACHE_AGE=999

    if [ "$CACHE_AGE" -ge 2 ]; then
        # Cache stale → drop old per-session files, run parallel detect into cache
        find "$STATUS_CACHE_DIR" -maxdepth 1 -name '*.status' -delete 2>/dev/null
        find "$STATUS_CACHE_DIR" -maxdepth 1 -name '*.ram' -delete 2>/dev/null
        while IFS='|' read -r sname _rest; do
            detect_claude_status "$sname" "$STATUS_CACHE_DIR/$sname.status" &
            get_session_ram      "$sname" "$STATUS_CACHE_DIR/$sname.ram" &
        done <<< "$SESSION_DATA"
        load_all_progress    # runs in foreground while detect runs in background
        wait
        touch "$CACHE_TS_FILE"
    else
        # Cache fresh — just load progress (small, also fast)
        load_all_progress
    fi
    # Pass 1 reads status + ram from STATUS_CACHE_DIR (whether fresh or cached)
    TMPDIR_SM="$STATUS_CACHE_DIR"

    # Common stats / state used by all views
    TOTAL_RAM=0; CURRENT_LINE=1
    SECTION_POS=""; DATA_LINES=""
    # Project header rule width — extend across the full popup width (no cap).
    # Subtract small margin (4) for popup borders/padding.
    SEP_W=$((TERM_W - 4))
    [ "$SEP_W" -lt 30 ] && SEP_W=30

if [ "$VIEW" = "sessions" ]; then
    # ── Pass 1: Collect raw fields per session (line built in Pass 2 with tree info) ──
    TAGGED_LINES=""
    TOTAL_W=0; TOTAL_I=0; TOTAL_SHELL=0; TOTAL_PROTECTED=0
    unset PKEY_COUNT PKEY_HAS_ORACLE PKEY_HAS_WORKER 2>/dev/null
    unset SUB_COUNT SUB_HAS_ORACLE SUB_HAS_WORKER 2>/dev/null
    declare -A PKEY_COUNT PKEY_HAS_ORACLE PKEY_HAS_WORKER
    declare -A SUB_COUNT SUB_HAS_ORACLE SUB_HAS_WORKER

    while IFS='|' read -r name wins attached activity created; do
        [ -z "$name" ] && continue
        # Hide transient launcher sessions (e.g. `_menu` spawned by c-menu outside tmux)
        [[ "$name" == _* ]] && continue
        panes=${SESSION_PANE_COUNT[$name]:-0}

        # Marker
        marker=" "
        [ "$name" = "$CURRENT_SESSION" ] && marker=">"
        [ "$attached" = "1" ] && [ "$name" != "$CURRENT_SESSION" ] && marker="*"

        # Age (formatted) + age in seconds
        age=""; age_secs=0
        if [ -n "$created" ] && [ "$created" -gt 0 ] 2>/dev/null; then
            age_secs=$((NOW-created))
            human_time "$age_secs"; age="$REPLY"
        fi

        # Protection badge (§ = 1-col BMP, guaranteed alignment)
        protect_icon=" "
        is_protected "$name" && { protect_icon="§"; TOTAL_PROTECTED=$((TOTAL_PROTECTED+1)); }

        # Claude status
        status_icon=" "; status_detail=""
        if [ -f "$TMPDIR_SM/$name.status" ]; then
            IFS='|' read -r st_status st_subagents st_claudes st_detail < "$TMPDIR_SM/$name.status"
            case "$st_status" in
                work)
                    TOTAL_W=$((TOTAL_W+1)); status_icon="●"
                    if [ "${st_subagents:-0}" -gt 0 ]; then status_detail="+${st_subagents}"
                    elif [ -n "$st_detail" ] && [ "$st_detail" != "active" ]; then status_detail="$st_detail"; fi
                    ;;
                idle) status_icon="○"; TOTAL_I=$((TOTAL_I+1)) ;;
                shell) status_icon="·"; TOTAL_SHELL=$((TOTAL_SHELL+1)) ;;
            esac
            auto_protect_check "$name" "$st_status"
        fi

        # RAM
        ram_str=""; ram_kb=0
        if [ -f "$TMPDIR_SM/$name.ram" ]; then
            read -r ram_kb < "$TMPDIR_SM/$name.ram"
            TOTAL_RAM=$((TOTAL_RAM + ram_kb))
            if [ "$ram_kb" -gt 100000 ]; then human_mb "$ram_kb"; ram_str="$REPLY"; fi
        fi

        # Git branch (cheap HEAD file read) — pane_path from pre-aggregated map
        pane_path="${SESSION_PANE_PATH[$name]:-}"
        branch=""
        if [ -n "$pane_path" ] && [ -f "$pane_path/.git/HEAD" ]; then
            head_ref=""
            read -r head_ref < "$pane_path/.git/HEAD" 2>/dev/null
            [ "${head_ref#ref: refs/heads/}" != "$head_ref" ] && branch="${head_ref#ref: refs/heads/}"
        fi

        col_ram="${ram_str}"
        col_branch=""
        if [ -n "$branch" ]; then truncate_str "$branch" 10; col_branch="$REPLY"; fi

        # Sort key: SECTION|PROJECT|ROLE|NAME — REPLY-style helpers, no fork.
        project_key "$name"; pkey="$REPLY"
        project_role "$name"; prole="$REPLY"
        case "$pkey" in
            Home)    section=1 ;;
            _system) section=3 ;;
            *)       section=2 ;;
        esac
        oracle_idx "$name"; oidx="$REPLY"
        sub_key="${pkey}::${oidx}"

        PKEY_COUNT[$pkey]=$((${PKEY_COUNT[$pkey]:-0}+1))
        [ "$prole" = "0" ] && PKEY_HAS_ORACLE[$pkey]=1
        [ "$prole" = "1" ] && PKEY_HAS_WORKER[$pkey]=1

        SUB_COUNT[$sub_key]=$((${SUB_COUNT[$sub_key]:-0}+1))
        [ "$prole" = "0" ] && SUB_HAS_ORACLE[$sub_key]=1
        [ "$prole" = "1" ] && SUB_HAS_WORKER[$sub_key]=1

        # Sort key now includes oracle_idx so sub-groups stay contiguous.
        # AISB orchestration progress (X/Y todos) — pre-loaded into PROGRESS_STATE
        # in one pass at the top of the loop. Lookup is O(1), no fork.
        progress_str="${PROGRESS_STATE[$name]:-}"

        # Field order: section|pkey|oidx|prole|name|marker|sicon|picon|ram|age|branch|ram_kb|age_secs|progress
        TAGGED_LINES+="${section}|${pkey}|${oidx}|${prole}|${name}|${marker}|${status_icon}|${protect_icon}|${col_ram}|${age}|${col_branch}|${ram_kb:-0}|${age_secs:-0}|${progress_str}"$'\n'
    done <<< "$SESSION_DATA"

    # ── Pass 2: Sort by section → pkey → oracle_idx → role → name ──
    # The oracle_idx column keeps each oracle's workers grouped under that oracle.
    SORTED=$(echo "$TAGGED_LINES" | sort -t'|' -k1,1 -k2,2 -k3,3n -k4,4n -k5,5)
    mapfile -t SORTED_ARR <<< "$SORTED"
    N=${#SORTED_ARR[@]}

    DISPLAY_LIST=" "$'\n'  # blank line after header
    LINE_NUM=1
    PREV_SECTION=""
    PREV_PKEY=""
    SECTION_POS=""  # space-separated 1-based line numbers (first session of each section)
    DATA_LINES=""   # space-separated 1-based line numbers of selectable session lines

    for ((idx=0; idx<N; idx++)); do
        line_data="${SORTED_ARR[$idx]}"
        [ -z "$line_data" ] && continue
        IFS='|' read -r section pkey oidx prole sname marker sicon picon col_ram age col_branch ram_kb age_secs progress_str <<< "$line_data"
        [ -z "$section" ] && continue
        sub_key="${pkey}::${oidx}"

        # ── Project header (Option E: flush-left label + hairline rule to width) ──
        if [ "$pkey" != "$PREV_PKEY" ]; then
            if [ -n "$PREV_PKEY" ]; then
                DISPLAY_LIST+=" "$'\n'
                LINE_NUM=$((LINE_NUM + 1))
            fi
            case "$pkey" in
                Home)    sec_label="Home" ;;
                _system) sec_label="system" ;;
                *)       sec_label="$pkey" ;;
            esac
            # Header line: "Causio ─────────────…" (label flush-left, no indent)
            trail_cols=$((SEP_W - ${#sec_label} - 1))
            [ "$trail_cols" -lt 0 ] && trail_cols=0
            trail=""; _i=0
            while [ "$_i" -lt "$trail_cols" ]; do trail+="─"; _i=$((_i+1)); done
            DISPLAY_LIST+="${sec_label} ${trail}"$'\n'
            LINE_NUM=$((LINE_NUM + 1))
            SECTION_POS+="$((LINE_NUM + 1)) "  # first session of this project
        fi

        # ── Tree decoration (per sub-group: oracle + ITS workers) ──
        # Drawn only when the (pkey, oracle_idx) sub-group has BOTH oracle and worker.
        # Multi-oracle projects: each oracle's workers nest under that oracle, not
        # all-workers-of-the-project.
        deco=""
        deco_cols=0
        has_tree=0
        if [ "${SUB_HAS_ORACLE[$sub_key]:-0}" = "1" ] && [ "${SUB_HAS_WORKER[$sub_key]:-0}" = "1" ]; then
            has_tree=1
        fi
        if [ "$prole" != "4" ] && [ "$has_tree" = "1" ] && [ "${SUB_COUNT[$sub_key]:-0}" -gt 1 ]; then
            # Compare sub_key (pkey + oidx) with neighbors, not just pkey
            prev_sub=""
            if [ $idx -gt 0 ]; then
                IFS='|' read -r _ p_pkey p_oidx _ _ _ _ _ _ _ _ _ <<< "${SORTED_ARR[$((idx-1))]}"
                prev_sub="${p_pkey}::${p_oidx}"
            fi
            next_sub=""
            if [ $((idx+1)) -lt $N ]; then
                IFS='|' read -r _ n_pkey n_oidx _ _ _ _ _ _ _ _ _ <<< "${SORTED_ARR[$((idx+1))]}"
                next_sub="${n_pkey}::${n_oidx}"
            fi
            if [ "$prev_sub" != "$sub_key" ]; then
                deco=""                   # root oracle of this sub-group
                deco_cols=0
            elif [ "$next_sub" != "$sub_key" ]; then
                deco="  └ "                # last child (indented under parent oracle)
                deco_cols=4
            else
                deco="  ├ "                # middle child
                deco_cols=4
            fi
        fi

        # Display name: strip redundant project prefix (REPLY-style, no fork)
        short_name "$sname" "$pkey"; display_name="$REPLY"

        # Smart truncate: workers reverse-truncate, others normal
        avail=$((NAME_MAX - deco_cols))
        if [ "$prole" = "1" ]; then
            truncate_smart "$display_name" "$avail" "start"
        else
            truncate_smart "$display_name" "$avail" "end"
        fi
        tname="$REPLY"

        # Pad name to fill (NAME_MAX - deco_cols) display columns.
        # truncate_smart adds at most ONE "…" (U+2026, 3 bytes / 1 col) → bytes - 2 = visible cols
        # when ellipsis is present. Avoids forking awk per session line.
        visible_cols=${#tname}
        case "$tname" in *…*) visible_cols=$((visible_cols - 2)) ;; esac
        name_spaces=$((avail - visible_cols))
        [ "$name_spaces" -lt 0 ] && name_spaces=0
        pad_name=$(printf "%-${name_spaces}s" "")

        # ── RAM warning: > 1 GB → red ──
        if [ "${ram_kb:-0}" -gt 1048576 ] 2>/dev/null; then
            col_ram="${RED}${col_ram}${RST}"
        fi

        # Age bar (8) + AISB progress field (19, fixed) + RAM + age + branch.
        age_bar "${age_secs:-0}"; bar="$REPLY"
        progress_field=$(printf '%19s' "")
        if [ -n "$progress_str" ]; then
            has_blocked=0
            ps_clean="$progress_str"
            case "$ps_clean" in *⚠) has_blocked=1; ps_clean="${ps_clean%⚠}" ;; esac
            done_n="${ps_clean%%/*}"
            total_n="${ps_clean##*/}"
            pct=0
            [ "${total_n:-0}" -gt 0 ] 2>/dev/null && pct=$((done_n * 100 / total_n))
            filled=$((pct * 10 / 100))
            [ "$filled" -gt 10 ] && filled=10
            pbar=""
            for ((i=0; i<10; i++)); do
                if [ "$i" -lt "$filled" ]; then pbar+="━"; else pbar+="─"; fi
            done
            warn_glyph=" "
            [ "$has_blocked" -eq 1 ] && warn_glyph="⚠"
            printf -v progress_field "[%s] %3d%% %s" "$pbar" "$pct" "$warn_glyph"
        fi
        # Two halves: name+bar+progress (left) | flex gap | ram+age+branch (flush right at popup edge).
        # Aligns the right trio with the cpu/ram/disk stats in the header.
        printf -v left_half "%-8s  %s" "$bar" "$progress_field"
        printf -v far_right "%5s %6s %10s" "$col_ram" "$age" "$col_branch"

        # Total visible cols = TERM_W - 4 (popup border margin):
        #   prefix(8) + (deco+tname+pad = NAME_MAX) + 4sp + left_half(29) + GAP + far_right(23)
        EFFECTIVE_W=$((TERM_W - 4))
        gap_n=$((EFFECTIVE_W - 8 - NAME_MAX - 4 - 29 - 23))
        [ "$gap_n" -lt 1 ] && gap_n=1
        gap=$(printf '%*s' "$gap_n" "")

        line="${marker} ${sicon} ${picon} │ ${deco}${tname}${pad_name}    ${left_half}${gap}${far_right}"$'\t'"${sname}"
        DISPLAY_LIST+="${line}"$'\n'
        LINE_NUM=$((LINE_NUM + 1))
        # Killed entries (prole=4, only present in historique view) are visible but
        # not navigable via skip-nav — switch-client would fail anyway.
        if [ "$prole" != "4" ]; then
            DATA_LINES+="${LINE_NUM} "
            [ "$sname" = "$CURRENT_SESSION" ] && CURRENT_LINE=$LINE_NUM
        fi

        PREV_SECTION="$section"
        PREV_PKEY="$pkey"
    done

    # Remove trailing blank, no footer (actions moved to "menu" tab)
    DISPLAY_LIST=$(echo -n "$DISPLAY_LIST" | sed '/^$/d')

elif [ "$VIEW" = "historique" ]; then
    # Historique view: list killed sessions grouped by project, newest first.
    # Press Enter on any entry → recreates the tmux session at the project's path
    # so you can resume work where you left off.
    unset HIST_BY_PKEY 2>/dev/null
    declare -A HIST_BY_PKEY
    if [ -s "$HISTORY_FILE" ]; then
        while IFS= read -r kentry; do
            ktime=$(printf '%s' "$kentry" | awk -F' \\| ' '{print $1}')
            kname=$(printf '%s' "$kentry" | awk -F' \\| ' '{print $2}')
            kreason=$(printf '%s' "$kentry" | awk -F' \\| ' '{print $3}')
            [ -z "$kname" ] && continue
            project_key "$kname"; kpkey="$REPLY"
            HIST_BY_PKEY[$kpkey]+="${ktime}|${kname}|${kreason}"$'\n'
        done < "$HISTORY_FILE"
    fi

    DISPLAY_LIST=" "$'\n'
    LINE_NUM=1
    DATA_LINES=""
    CURRENT_LINE=1

    if [ ${#HIST_BY_PKEY[@]} -eq 0 ]; then
        DISPLAY_LIST+="  (no killed sessions yet — kill some and they'll appear here)"$'\n'
    else
        # Order: Home first, _system last, others alpha
        ordered=()
        [ -n "${HIST_BY_PKEY[Home]:-}" ] && ordered+=("Home")
        for k in $(printf '%s\n' "${!HIST_BY_PKEY[@]}" | sort); do
            [ "$k" = "Home" ] || [ "$k" = "_system" ] && continue
            ordered+=("$k")
        done
        [ -n "${HIST_BY_PKEY[_system]:-}" ] && ordered+=("_system")

        first_proj=1
        for pkey in "${ordered[@]}"; do
            sec_label="$pkey"
            [ "$pkey" = "_system" ] && sec_label="system"
            if [ $first_proj -eq 0 ]; then
                DISPLAY_LIST+=" "$'\n'
                LINE_NUM=$((LINE_NUM + 1))
            fi
            first_proj=0
            # Project header (Option E flush-left rule)
            trail_cols=$((SEP_W - ${#sec_label} - 1))
            [ "$trail_cols" -lt 0 ] && trail_cols=0
            trail=""; _i=0
            while [ "$_i" -lt "$trail_cols" ]; do trail+="─"; _i=$((_i+1)); done
            DISPLAY_LIST+="${sec_label} ${trail}"$'\n'
            LINE_NUM=$((LINE_NUM + 1))

            # Entries newest first (history file is appended chronologically)
            entries="${HIST_BY_PKEY[$pkey]}"
            while IFS='|' read -r ktime kname kreason; do
                [ -z "$kname" ] && continue
                short_name "$kname" "$pkey"; short="$REPLY"
                avail=$((NAME_MAX))
                case "$kname" in
                    *-worker-*) truncate_smart "$short" "$avail" "start" ;;
                    *)          truncate_smart "$short" "$avail" "end" ;;
                esac
                tn="$REPLY"
                vc=$(LC_ALL=C.UTF-8 awk -v s="$tn" 'BEGIN{print length(s)}')
                ns=$((avail - vc))
                [ "$ns" -lt 0 ] && ns=0
                pn=$(printf "%-${ns}s" "")
                # Layout: ✗ space space space │ space name pad  time(5) reason(rest)
                # Matches sessions visual "marker sicon picon │ name" (sicon/picon blank for killed)
                printf -v line_text "✗     │ %s%s  %-7s %s" "$tn" "$pn" "$ktime" "${kreason:-killed}"
                DISPLAY_LIST+="${line_text}"$'\t'"${kname}"$'\n'
                LINE_NUM=$((LINE_NUM + 1))
                DATA_LINES+="${LINE_NUM} "
                [ "$CURRENT_LINE" -eq 1 ] && CURRENT_LINE=$LINE_NUM   # focus first entry
            done <<< "$(echo "$entries" | tac)"
        done
    fi

elif [ "$VIEW" = "menu" ]; then
    # Menu view: action buttons. Each line is selectable; CHOICE-grep handlers
    # in the main loop trigger the action.
    DISPLAY_LIST=" "$'\n'
    DISPLAY_LIST+="  ◆ new hermes          Hermes Agent (Nous Research)"$'\n'
    DISPLAY_LIST+="  ◆ new gemini          Gemini 2.5 Pro (Google)"$'\n'
    DISPLAY_LIST+="  ◆ new claude          Claude Opus 4.7 (Anthropic)"$'\n'
    DISPLAY_LIST+="  ◆ new codex           Codex CLI (OpenAI)"$'\n'
    DISPLAY_LIST+="  ◆ new pi              Pi Agent (Earendil)"$'\n'
    DISPLAY_LIST+="  ◆ aisb terminal       Attach AISB bot logs"$'\n'
    DISPLAY_LIST+=" "$'\n'
    DISPLAY_LIST+="  open project          pick a project from projects.json"$'\n'
    DISPLAY_LIST+="  clean cache           drop kernel cache + /tmp junk (fast)"$'\n'
    DISPLAY_LIST+="  deep clean            heavy disk reclaim — npm/bun/pnpm/playwright/electron/journal/apt"$'\n'
    DISPLAY_LIST+="  clean history         wipe kill log + protection state"$'\n'
    DISPLAY_LIST+="  kill all              kill every session except the current one"$'\n'
    DATA_LINES="2 3 4 5 6 7 9 10 11 12 13"
    CURRENT_LINE=2

elif [ "$VIEW" = "help" ]; then
    # Help view: keyboard shortcuts + status icon legend, fully searchable.
    DISPLAY_LIST=""
    add_help_line() {
        DISPLAY_LIST+="${1}"$'\n'
        HELP_LN=$((HELP_LN+1))
        # Mark non-blank lines as data so down/up skip blank rows
        case "$1" in *[!\ ]*) DATA_LINES+="${HELP_LN} " ;; esac
    }
    HELP_LN=0
    add_help_line " "
    add_help_line "  Tabs"
    add_help_line "    ← / <        previous tab"
    add_help_line "    → / >        next tab  (sessions ↔ menu ↔ help)"
    add_help_line " "
    add_help_line "  Navigation"
    add_help_line "    ↑ / ↓        move between sessions (skips blanks + headers)"
    add_help_line "    Tab          jump to next project group"
    add_help_line "    ⇧Tab         spawn new ClaudeRoot session at \$HOME"
    add_help_line "    Enter        switch to selected session / run menu action"
    add_help_line "    Esc          close menu"
    add_help_line " "
    add_help_line "  Session actions"
    add_help_line "    x            kill selected session"
    add_help_line "    .            toggle kill protection (§ icon)"
    add_help_line "    §            refresh in-place — reloads list (progress, age, RAM) + preview"
    add_help_line "    ?            jump to this help tab"
    add_help_line " "
    add_help_line "  Status icons (column 2 of each session line)"
    add_help_line "    ●  working   Claude is actively running"
    add_help_line "    ○  idle      Claude at prompt, waiting for input"
    add_help_line "    ·  shell     no Claude in this session"
    add_help_line "    §  pinned    immune to orphan-killer and 'x' kill"
    add_help_line "    >  current   the session you are attached to"
    add_help_line "    *  attached  an attached client other than yours"
    add_help_line "    ✗  killed    session was closed"
    add_help_line " "
    add_help_line "  Tree glyphs (workers under their oracle)"
    add_help_line "    ├ / └        worker child of the oracle directly above"
    add_help_line "                 (drawn only when group has both oracle and worker)"
    add_help_line " "
    add_help_line "  Project groups"
    add_help_line "    Home         Home, Home-2, c-* (interactive sessions)"
    add_help_line "    <Project>    one header per project (Causio, Kommu, …)"
    add_help_line "    system       earthbit-*, AISB-* (orchestration daemons)"
    add_help_line " "
    add_help_line "  Auto-protect"
    add_help_line "    Working sessions are auto-protected. After 10 min idle,"
    add_help_line "    protection is removed. Manual '.' override is respected."
    CURRENT_LINE=2
    unset -f add_help_line

fi

    human_mb "$TOTAL_RAM"; TOTAL_RAM_STR="$REPLY"

    # Header: tabs (left) + stats (right) on line 1, underline on line 2.
    TAB_BAR=$(render_tabs "$VIEW")
    TAB_LINE1=$(printf '%s' "$TAB_BAR" | sed -n '1p')
    TAB_LINE2=$(printf '%s' "$TAB_BAR" | sed -n '2p')
    STATS_STR="cpu ${CPU}%   ram ${RAM}%   disk ${DISK}   ${TOTAL_RAM_STR}"

    # Compute right-aligned padding (visible chars only — strip ANSI from tab line)
    tab_visible=$(printf '%s' "$TAB_LINE1" | sed 's/\x1b\[[0-9;]*m//g')
    tab_w=$(LC_ALL=C.UTF-8 awk -v s="$tab_visible" 'BEGIN{print length(s)}')
    stats_w=${#STATS_STR}
    target_w=$((TERM_W - 4))      # match popup margin so stats never get cut off
    pad_n=$((target_w - tab_w - stats_w))
    [ "$pad_n" -lt 3 ] && pad_n=3
    pad=$(printf '%*s' "$pad_n" "")

    HEADER=" "$'\n'
    HEADER+="${TAB_LINE1}${pad}${STATS_STR}"$'\n'
    HEADER+="${TAB_LINE2}"$'\n'
    HEADER+=" "

    # Persist line numbers used by fzf bind helpers
    echo "$SECTION_POS" > /tmp/.sm-sections        # Tab section-cycle
    echo "$DATA_LINES"  > /tmp/.sm-data-lines      # Down/Up skip-empty
    echo 0 > /tmp/.sm-section-cursor

    # Preview command — skip menu items (open project / clean RAM / kill all / separators / group headers)
    # Preview: {2} = the hidden tab field that holds the full session name.
    # Empty for headers / blank lines / menu actions → no preview shown.
    PREVIEW_CMD='sess={2}; [ -n "$sess" ] && '"$HOME"'/.tmux/scripts/session-preview.sh "$sess" "'"$TMPDIR_SM"'"'

    # Render-only mode: dump DISPLAY_LIST to stdout (used by `reload(...)` bind on §)
    if [ "$SM_RENDER_MODE" = "list" ]; then
        printf '%s' "$DISPLAY_LIST"
        exit 0
    fi

    # Bind §: reload list in-place + refresh preview pane (no popup flash).
    # SM_TERM_W passes the popup width to the --render child (which has no tty).
    RELOAD_CMD="SM_TERM_W=$TERM_W $HOME/.tmux/scripts/session-manager-v2.sh --render $VIEW"

    SELECTED=$(echo "$DISPLAY_LIST" | fzf \
        --ansi \
        --sync \
        --no-multi \
        --reverse \
        --no-info \
        --no-separator \
        --header-first \
        --header="$HEADER" \
        --expect="x,.,?,shift-tab,<,>,left,right" \
        --pointer=" " \
        --prompt="  search > " \
        --border=none \
        --delimiter=$'\t' \
        --with-nth=1 \
        --bind "start:pos($CURRENT_LINE)" \
        --bind "§:refresh-preview+reload($RELOAD_CMD)" \
        --bind "tab:transform($HOME/.tmux/scripts/sm-tab-next.sh)" \
        --bind "down:transform($HOME/.tmux/scripts/sm-skip-nav.sh +1)" \
        --bind "up:transform($HOME/.tmux/scripts/sm-skip-nav.sh -1)" \
        --bind "ctrl-n:transform($HOME/.tmux/scripts/sm-skip-nav.sh +1)" \
        --bind "ctrl-p:transform($HOME/.tmux/scripts/sm-skip-nav.sh -1)" \
        --preview="$PREVIEW_CMD" \
        --preview-window=down,40%,~2,follow \
        --color="fg:-1,bg:-1,hl:-1:underline,fg+:0:bold,bg+:7,hl+:1:bold:underline,info:-1,prompt:-1,pointer:-1,marker:-1,spinner:-1,header:-1:dim,border:-1,preview-fg:-1,preview-bg:-1,gutter:-1")

    KEY=$(echo "$SELECTED" | head -1)
    CHOICE=$(echo "$SELECTED" | tail -1)

    # Tab cycling: ← / < = previous, → / > = next
    case "$KEY" in
        "<"|"left")
            case "$VIEW" in
                sessions)   VIEW=help ;;
                menu)       VIEW=sessions ;;
                help)       VIEW=menu ;;
            esac
            continue ;;
        ">"|"right")
            case "$VIEW" in
                sessions)   VIEW=menu ;;
                menu)       VIEW=help ;;
                help)       VIEW=sessions ;;
            esac
            continue ;;
    esac

    [ -z "$CHOICE" ] && exit 0
    # Real session/historique lines carry a trailing TAB + full name. Anything
    # without a TAB is a header / blank / separator → skip. Menu actions also
    # have no tab but are detected by their literal text below.
    case "$CHOICE" in
        *$'\t'*) ;;  # session or historique entry — proceed
        *'open project'*|*'clean cache'*|*'deep clean'*|*'clean history'*|*'kill all'*|*'new hermes'*|*'new claude'*|*'new codex'*|*'aisb terminal'*) ;;  # menu action
        *) continue ;;  # header / blank / decorative
    esac

    # "?" key = jump to help tab
    if [ "$KEY" = "?" ]; then
        VIEW="help"
        continue
    fi

    # Shift+Tab = spawn fresh Claude Code session at $HOME (n1 in c-menu).
    # (fzf does not support alt-tab; shift-tab is the closest Tab variant available.)
    if [ "$KEY" = "shift-tab" ]; then
        new_name="ClaudeRoot"
        _i=2
        while tmux has-session -t "$new_name" 2>/dev/null; do
            new_name="ClaudeRoot-$_i"; ((_i++))
        done
        tmux new-session -d -s "$new_name" -c "$HOME"
        tmux set-environment -t "$new_name" -u ANTHROPIC_API_KEY
        tmux set-option -t "$new_name" remain-on-exit on
        tmux send-keys -t "$new_name" "claude --dangerously-skip-permissions" Enter
        tmux switch-client -t "$new_name"
        exit 0
    fi

    # Action: new hermes (Nous Research Hermes Agent)
    if echo "$CHOICE" | grep -q 'new hermes'; then
        _name="Hermes"; _i=2
        while tmux has-session -t "$_name" 2>/dev/null; do
            _name="Hermes-$_i"; ((_i++))
        done
        tmux new-session -d -s "$_name" -c "$HOME"
        tmux send-keys -t "$_name" 'hermes' Enter
        tmux switch-client -t "$_name"
        exit 0
    fi

    # Action: new gemini (Google Gemini CLI)
    if echo "$CHOICE" | grep -q 'new gemini'; then
        _name="Gemini"; _i=2
        while tmux has-session -t "$_name" 2>/dev/null; do
            _name="Gemini-$_i"; ((_i++))
        done
        tmux new-session -d -s "$_name" -c "$HOME"
        tmux send-keys -t "$_name" '$HOME/.npm-global/bin/gemini' Enter
        tmux switch-client -t "$_name"
        exit 0
    fi

    # Action: new claude (Claude Code)
    if echo "$CHOICE" | grep -q 'new claude'; then
        _name="Claude"; _i=2
        while tmux has-session -t "$_name" 2>/dev/null; do
            _name="Claude-$_i"; ((_i++))
        done
        tmux new-session -d -s "$_name" -c "$HOME"
        tmux send-keys -t "$_name" 'claude' Enter
        tmux switch-client -t "$_name"
        exit 0
    fi

    # Action: new codex (OpenAI Codex)
    if echo "$CHOICE" | grep -q 'new codex'; then
        _name="Codex"; _i=2
        while tmux has-session -t "$_name" 2>/dev/null; do
            _name="Codex-$_i"; ((_i++))
        done
        tmux new-session -d -s "$_name" -c "$HOME"
        tmux set-environment -t "$_name" -u OPENAI_API_KEY
        tmux send-keys -t "$_name" 'unset OPENAI_API_KEY && codex' Enter
        tmux switch-client -t "$_name"
        exit 0
    fi

    # Action: new pi (Pi Agent)
    if echo "$CHOICE" | grep -q 'new pi'; then
        _name="Pi"; _i=2
        while tmux has-session -t "$_name" 2>/dev/null; do
            _name="Pi-$_i"; ((_i++))
        done
        tmux new-session -d -s "$_name" -c "$HOME"
        sleep 0.5
        tmux send-keys -t "$_name" 'pi' Enter
        sleep 0.5
        tmux switch-client -t "$_name" 2>/tmp/pi-switch-debug.log
        exit 0
    fi

    # Action: aisb terminal (attach to bot logs)
    if echo "$CHOICE" | grep -q 'aisb terminal'; then
        if tmux has-session -t AISB-ORACLE 2>/dev/null; then
            tmux switch-client -t AISB-ORACLE
        else
            tmux new-window -n 'aisb-logs' 'journalctl --user -u aisb-bot -f'
        fi
        exit 0
    fi

    # Action: open project — reads from ~/.config/tmux-claude/projects.conf
    # (generated by project-analyzer.sh) with optional fallback to legacy
    # AISB projects.json. Falls back to scanning a few common dirs as a
    # last resort if neither config exists.
    if echo "$CHOICE" | grep -q 'open project'; then
        PROJECTS_CONF="$HOME/.config/tmux-claude/projects.conf"
        PROJECTS_JSON="$HOME/VibeCoding/agentic/agentik-monitor/bot/projects.json"
        # Home always first (shell-only, no Claude auto-launch)
        PROJECT_LINES=$(printf '  %-25s  %s' "Home" "~")
        unset PROJ_PATH_MAP 2>/dev/null
        declare -A PROJ_PATH_MAP

        if [ -f "$PROJECTS_CONF" ]; then
            while IFS='|' read -r pname ppath pcat _rest; do
                [[ "$pname" == \#* || -z "$pname" ]] && continue
                ppath="${ppath%%#*}"; ppath="${ppath%%[[:space:]]}"
                [ -d "$ppath" ] || continue
                PROJ_PATH_MAP[$pname]="$ppath"
            done < "$PROJECTS_CONF"
        fi
        if [ -f "$PROJECTS_JSON" ] && command -v jq >/dev/null 2>&1; then
            while IFS='|' read -r pname ppath; do
                [ -n "${PROJ_PATH_MAP[$pname]:-}" ] && continue
                [ -d "$ppath" ] && PROJ_PATH_MAP[$pname]="$ppath"
            done < <(jq -r '.projects | to_entries[] | "\(.key)|\(.value.path)"' "$PROJECTS_JSON" 2>/dev/null)
        fi

        # Render project list — sorted, paths shortened relative to $HOME
        if [ ${#PROJ_PATH_MAP[@]} -gt 0 ]; then
            db_lines=$(for k in "${!PROJ_PATH_MAP[@]}"; do echo "$k|${PROJ_PATH_MAP[$k]}"; done | sort -f \
                | while IFS='|' read -r pname ppath; do
                    short="${ppath#$HOME/}"
                    [ "$short" = "$ppath" ] || short="~/$short"
                    printf '  %-25s  %s\n' "$pname" "$short"
                done)
            [ -n "$db_lines" ] && PROJECT_LINES="${PROJECT_LINES}"$'\n'"${db_lines}"
        fi

        PROJ_SELECTED=$(echo "$PROJECT_LINES" | fzf \
            --no-multi --reverse --no-info \
            --header="Select project  Enter=open  Esc=back" \
            --prompt="" --pointer=" " --border=none \
            --color="fg:-1,bg:-1,hl:-1:underline,fg+:0:bold,bg+:7,hl+:1:bold:underline,info:-1,prompt:-1,pointer:-1,marker:-1,spinner:-1,header:-1:dim,border:-1,preview-fg:-1,preview-bg:-1,gutter:-1")

        [ -z "$PROJ_SELECTED" ] && continue

        PROJ_NAME=$(echo "$PROJ_SELECTED" | awk '{print $1}')
        if [ "$PROJ_NAME" = "Home" ]; then
            PROJ_PATH="$HOME"
            HOME_MODE=1
        else
            PROJ_PATH="${PROJ_PATH_MAP[$PROJ_NAME]:-}"
            HOME_MODE=0
        fi
        { [ -z "$PROJ_PATH" ] || [ ! -d "$PROJ_PATH" ]; } && continue

        if ! tmux has-session -t "$PROJ_NAME" 2>/dev/null; then
            NEW_SESS="$PROJ_NAME"
        else
            _i=2
            while tmux has-session -t "${PROJ_NAME}-${_i}" 2>/dev/null; do ((_i++)); done
            NEW_SESS="${PROJ_NAME}-${_i}"
        fi
        tmux new-session -d -s "$NEW_SESS" -c "$PROJ_PATH"
        # Home = shell only (no Claude). Projects = auto-launch Claude.
        if [ "$HOME_MODE" != "1" ]; then
            tmux send-keys -t "$NEW_SESS" "claude --dangerously-skip-permissions" Enter
        fi
        tmux switch-client -t "$NEW_SESS"
        exit 0
    fi

    # Action: clean cache (fast — kernel page cache + /tmp junk)
    if echo "$CHOICE" | grep -q 'clean cache'; then
        sync
        echo 3 | sudo tee /proc/sys/vm/drop_caches > /dev/null 2>&1
        rm -rf /tmp/.maniac-* /tmp/browser-screenshots/* /tmp/sm-test* 2>/dev/null
        continue
    fi

    # Action: deep clean (heavy disk reclaim — runs script with progress + pause)
    if echo "$CHOICE" | grep -q 'deep clean'; then
        clear
        bash "$HOME/.tmux/scripts/sm-deep-clean.sh"
        continue
    fi

    # Action: clean history (wipe kill log + protection state)
    if echo "$CHOICE" | grep -q 'clean history'; then
        clear
        bash "$HOME/.tmux/scripts/sm-clean-history.sh"
        continue
    fi

    # Action: kill all (except current)
    if echo "$CHOICE" | grep -q 'kill all'; then
        for s in $(tmux list-sessions -F '#{session_name}' 2>/dev/null | grep -v "^${CURRENT_SESSION}$"); do
            kill_with_history "$s" "kill-all"
        done
        continue
    fi

    # ── Session actions ──
    TARGET=$(extract_name "$CHOICE")

    # "." key = toggle protection
    if [ "$KEY" = "." ]; then
        if [ -n "$TARGET" ]; then
            toggle_protection "$TARGET"
            # If manually unprotecting, mark it so auto-protect doesn't re-protect
            if ! is_protected "$TARGET"; then
                touch "$PROTECT_DIR/${TARGET}.manual-unprotect"
            else
                rm -f "$PROTECT_DIR/${TARGET}.manual-unprotect"
            fi
        fi
        continue
    fi

    # "x" key = kill session
    if [ "$KEY" = "x" ]; then
        is_protected "$TARGET" && continue
        if [ "$TARGET" = "$CURRENT_SESSION" ]; then
            OTHER=$(tmux list-sessions -F '#{session_name}' | grep -v "^${TARGET}$" | head -1)
            if [ -n "$OTHER" ]; then
                tmux switch-client -t "$OTHER"
                CURRENT_SESSION="$OTHER"
                kill_with_history "$TARGET" "manual"
            fi
        else
            kill_with_history "$TARGET" "manual"
        fi
        continue
    fi

    # ── Historique view: Enter recreates the killed session at its project path ──
    if [ "$VIEW" = "historique" ] && [ -n "$TARGET" ]; then
        # If somehow it's already alive, just switch
        if tmux has-session -t "$TARGET" 2>/dev/null; then
            tmux switch-client -t "$TARGET"
            exit 0
        fi
        project_key "$TARGET"; rpkey="$REPLY"
        rpath=""
        case "$rpkey" in
            Home)    rpath="$HOME" ;;
            _system) clear; echo "  System sessions can't be reopened from history."; sleep 2; continue ;;
            *)
                # Look up project path: projects.conf first, then legacy projects.json
                PROJECTS_CONF="$HOME/.config/tmux-claude/projects.conf"
                if [ -f "$PROJECTS_CONF" ]; then
                    while IFS='|' read -r pname ppath _rest; do
                        [[ "$pname" == \#* || -z "$pname" ]] && continue
                        if [ "$pname" = "$rpkey" ]; then
                            ppath="${ppath%%#*}"; ppath="${ppath%%[[:space:]]}"
                            rpath="$ppath"
                            break
                        fi
                    done < "$PROJECTS_CONF"
                fi
                if [ -z "$rpath" ]; then
                    PROJECTS_JSON="$HOME/VibeCoding/agentic/agentik-monitor/bot/projects.json"
                    if [ -f "$PROJECTS_JSON" ] && command -v jq >/dev/null 2>&1; then
                        rpath=$(jq -r --arg n "$rpkey" '.projects[$n].path // empty' "$PROJECTS_JSON" 2>/dev/null)
                    fi
                fi
                [ -z "$rpath" ] && rpath="$HOME"
                ;;
        esac
        if [ ! -d "$rpath" ]; then
            clear; echo "  Project path missing: $rpath"; sleep 2; continue
        fi
        tmux new-session -d -s "$TARGET" -c "$rpath"
        tmux set-environment -t "$TARGET" -u ANTHROPIC_API_KEY
        tmux set-option -t "$TARGET" remain-on-exit on
        tmux switch-client -t "$TARGET"
        exit 0
    fi

    # Enter = switch to session
    [ -n "$TARGET" ] && [ "$TARGET" != "$CURRENT_SESSION" ] && tmux switch-client -t "$TARGET"
    exit 0
done
